name: Check NPM token
description: Check whether NPM_TOKEN is set and is an Automation token
inputs:
  npm-token:
    description: 'Optional npm token to use, overrides environment'
    required: false
outputs:
  result:
    description: 'Human-readable result of the check'
  token_available:
    description: 'true if NPM_TOKEN is available, false otherwise'

runs:
  using: 'composite'
  steps:
    - name: Use node to check npm token
      shell: bash
      run: |
        if [ -n "${{ inputs.npm-token }}" ]; then
          export NPM_TOKEN="${{ inputs.npm-token }}"
        fi
        RESULT=$(node ./scripts/check-npm-token-cli.js 2>&1 | grep -v "SECURITY NOTICE" | grep -v "npm notice" || echo "NPM_TOKEN check failed")
        echo "result=$RESULT" >> $GITHUB_OUTPUT
        if [ -n "$NPM_TOKEN" ]; then
          echo "token_available=true" >> $GITHUB_OUTPUT
        else
          echo "token_available=false" >> $GITHUB_OUTPUT
        fi